// <auto-generated />
using System;
using AUPExpert.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AUPExpert.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241031172457_Relacion[1-N][FlujoTrabajo_Tarea]+[1-N][Iteracion_Tarea]")]
    partial class Relacion1NFlujoTrabajo_Tarea1NIteracion_Tarea
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AUPExpert.Domain.Entities.Iteration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Codigo");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaFinal");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Objetivo");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("enum('INICIO','ELABORACION','CONSTRUCCION','TRANSICION')")
                        .HasColumnName("Fase");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int(11)")
                        .HasColumnName("ProyectoId");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("FechaInicio")
                        .HasDefaultValueSql("current_timestamp()");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ProjectId" }, "IdProyecto");

                    b.ToTable("Tbl_Iteraciones", (string)null);
                });

            modelBuilder.Entity("AUPExpert.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<ulong>("ConstructionPhaseCompleted")
                        .HasColumnType("bit(1)")
                        .HasColumnName("FaseConstruccionCompletada");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Descripcion");

                    b.Property<ulong>("ElaborationPhaseCompleted")
                        .HasColumnType("bit(1)")
                        .HasColumnName("FaseElaboracionCompletada");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaFinal");

                    b.Property<ulong>("InitialPhaseCompleted")
                        .HasColumnType("bit(1)")
                        .HasColumnName("FaseInicialCompletada");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nombre");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("FechaInicio")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('PENDIENTE','FINALIZADO')")
                        .HasDefaultValue("PENDIENTE")
                        .HasColumnName("Estado");

                    b.Property<ulong>("TransitionPhaseCompleted")
                        .HasColumnType("bit(1)")
                        .HasColumnName("FaseTransitionCompletada");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("Tbl_Proyectos", (string)null);
                });

            modelBuilder.Entity("AUPExpert.Domain.Entities.WorkFlow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Descripcion");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Nombre");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int(11)")
                        .HasColumnName("ProyectoId");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ProjectId" }, "ProyectoId");

                    b.ToTable("Tbl_FlujoTrabajo", (string)null);
                });

            modelBuilder.Entity("AUPExpert.Domain.Entities.WorkFlowTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Descripcion");

                    b.Property<int>("IterationId")
                        .HasColumnType("int(11)")
                        .HasColumnName("IteracionId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("varchar(75)")
                        .HasColumnName("Nombre");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("enum('BAJA','MEDIA','ALTA')")
                        .HasColumnName("Prioridad");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("enum('PENDIENTE','INICIADA','FINALIZADA')")
                        .HasColumnName("Estado");

                    b.Property<int>("WorkFlowId")
                        .HasColumnType("int(11)")
                        .HasColumnName("FlujoTrabajoId");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "WorkFlowId" }, "FlujoTrabajoId");

                    b.HasIndex(new[] { "IterationId" }, "IteracionId");

                    b.ToTable("Tbl_Tareas", (string)null);
                });

            modelBuilder.Entity("AUPExpert.Domain.Entities.Iteration", b =>
                {
                    b.HasOne("AUPExpert.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("project_iteration_fk");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AUPExpert.Domain.Entities.WorkFlow", b =>
                {
                    b.HasOne("AUPExpert.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("project_workflow_fk");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AUPExpert.Domain.Entities.WorkFlowTask", b =>
                {
                    b.HasOne("AUPExpert.Domain.Entities.Iteration", "Iteration")
                        .WithMany()
                        .HasForeignKey("IterationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("iteracion_tarea_fk");

                    b.HasOne("AUPExpert.Domain.Entities.WorkFlow", "WorkFlow")
                        .WithMany()
                        .HasForeignKey("WorkFlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("flujoTrabajo_tarea_fk");

                    b.Navigation("Iteration");

                    b.Navigation("WorkFlow");
                });
#pragma warning restore 612, 618
        }
    }
}
